name: "nowTalk Server"
description: "The ComBadge nowTalk Server"

version: "1.1.3"
slug: "nowtalk_server"

url: https://github.com/LumenSoftNL/nowTalk2.0

arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386

discovery:
  - wyoming
map:
  - share
  - config

panel_icon: mdi:account-voice
homeassistant: 2024.07.0

options:
  commport: "com20"
  baudrate: "921600"
  database: "./nowTalk.sqlite"
  serverName: "Bosdrift228"
  callname: "computer"
  dynamicExtIP: false
  externelIP: false
  allowGuests: true
  webAddress: "*"
  webPort: "12158"
  allowNewDevice: true
  sound_enabled: true
  noise_suppression: 0
  auto_gain: 0
  mic_volume_multiplier: 1.0
  sound_volume_multiplier: 1.0
  debug_logging: false

schema:
  commport: "com20"
  baudrate: int
  database: str
  serverName: str
  callname: str
  dynamicExtIP: bool
  externelIP: bool
  allowGuests: bool
  webAddress: str
  webPort: int

  sound_enabled: bool
  noise_suppression: int
  auto_gain: int
  mic_volume_multiplier: float
  sound_volume_multiplier: float
  debug_logging: bool


audio: true

image: LumenSoftNL/{arch}-nowtalk-server

ports:
  12158/tcp: 12158


startup: "services"
boot: "auto"

init: false
host_network: true
homeassistant_api: true
hassio_api: true

usb: true

auth_api: true

ingress: true
ingress_port: 0
