name: "nowTalk Server"
description: "The ComBadge nowTalk Server"

version: "1.1.58"
slug: "nowtalk_srv"

url: https://github.com/LumenSoftNL/nowTalk2.0

arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386

#discovery:
#  - combadge

panel_icon: mdi:account-voice
homeassistant: 2024.6.0

options:
  serialport: ""
  audio:
    sound_enabled: true
    noise_suppression: 0
    auto_gain: 0
    mic_volume_multiplier: 1.0
    sound_volume_multiplier: 1.0
  debug_logging: false

schema:
  serialport: device(subsystem=tty)
  baudrate: int?
  database: str?
  server_name: str?
  call_name: str?

  external_ip: str?
  dynamic_ext_ip: bool?
  allow_guests: bool?

  allow_new_device: bool?
  audio:
    sound_enabled: bool
    noise_suppression: int
    auto_gain: int
    mic_volume_multiplier: float
    sound_volume_multiplier: float
  debug_logging: bool

ports:
  12158/tcp: 12158

init: false
startup: "services"
boot: "auto"

#host_network: true
#homeassistant_api: true
#$hassio_api: true
#audio: true
#usb: true
#auth_api: true

#uart: true
#devicetree: true

ingress: true
ingress_port: 8099
