name: "nowTalk Server"
description: "The ComBadge nowTalk Server"

version: "1.1.23"
slug: "nowtalk_srv"

url: https://github.com/LumenSoftNL/nowTalk2.0

arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386

discovery:
  - ComBadge

panel_icon: mdi:account-voice
homeassistant: 2024.06.0

options:
  commport: none
  baudrate: "115200"
  dynamicExtIP: false
  externelIP: false
  allowGuests: true
  webAddress: "*"
  allowNewDevice: true
  audio:
    sound_enabled: true
    noise_suppression: 0
    auto_gain: 0
    mic_volume_multiplier: 1.0
    sound_volume_multiplier: 1.0
  debug_logging: false

schema:
  commport: str
  baudrate: int?
  database: str?
  serverName: str?
  callname: str?
  dynamicExtIP: bool?
  externelIP: bool?
  allowGuests: bool?
  webAddress: str?
  webPort: int?
  allowNewDevice: bool?
  audio:
    sound_enabled: bool
    noise_suppression: int
    auto_gain: int
    mic_volume_multiplier: float
    sound_volume_multiplier: float
  debug_logging: bool

ports:
  12158/tcp: 12158

init: false
startup: "services"
boot: "auto"

host_network: true
homeassistant_api: true
hassio_api: true
audio: true
usb: true
auth_api: true
ingress: true
